# Generated by Django 5.2.1 on 2025-05-24 22:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0002_visitrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitRequest',
            new_name='VisitSubmission',
        ),
        migrations.RenameField(
            model_name='visitsubmission',
            old_name='submitted_at',
            new_name='submitted_on',
        ),
    ]
